Repository WildCodeSchool/2022-03-php-orleans-project-tissusjaures, pull requests merged in 2022-05, with the labels that each got.

#141 S2 us9 categoriestipsandtricks
  database.sql
  public/assets/css/tips.css
  src/Controller/TipsController.php
  src/Model/TipCategoryManager.php
  src/View/Tips/tips.html.twig
  src/routes.php
Labels: Reviewed, Conflicts resolved

#236 Fix b footer
  public/assets/css/footer.css
  public/assets/css/style.css
  src/View/Component/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#237 Css fix
  public/assets/css/home.css
  public/assets/css/navbarStyle.css
  public/assets/css/style.css
  public/assets/images/headermain.jpeg
  public/assets/images/textured-stripes.png
  src/View/Component/_slogan.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed, Corrections done, Fix

#235 change font size and size for the monthly tip
  public/assets/css/tips.css
  src/View/Tips/tips.html.twig
Labels: Conflicts resolved

#241 layout_fix
  src/View/layout.html.twig
Labels: Reviewed, Fix

#239 Fix css produits
  public/assets/css/products.css
  src/View/Products/index.html.twig
  src/View/Products/tissus.html.twig
Labels: Reviewed, Corrections done

#242 Fix conflit s2 us10 card tip
  database.sql
  public/assets/css/tips.css
  public/assets/images/tache.jpg
  public/assets/images/tachebougie.jpg
  public/assets/images/tachepeinture.jpg
  public/assets/images/toileciree.jpeg
  src/Controller/TipsController.php
  src/Model/TipsManager.php
  src/View/Tips/tips.html.twig
Labels: Reviewed

#240 Admin cloth fix
  public/assets/css/adminstyle.css
  src/View/Admin/Cloth/_form.html.twig
  src/View/Admin/Cloth/show.html.twig
  src/View/adminLayout.html.twig
Labels: Reviewed, Corrections done, Fix

#243 S3 us35 admin show cat tissus
  src/Controller/AdminClothCategoryController.php
  src/View/Admin/ClothCategory/index.html.twig
  src/routes.php
Labels: Reviewed

#246 images now nullable, fixed wrong urls
  database.sql
Labels: Reviewed, Fix

#248 navbar admin 1.0
  src/View/Admin/Component/_navbar.html.twig
  src/View/adminLayout.html.twig
Labels: Reviewed

#251 AddLexicon 1.0
  src/Controller/AdminLexiconController.php
  src/Model/AdminLexiconManager.php
  src/View/Admin/Lexicon/_form.html.twig
  src/View/Admin/Lexicon/add.html.twig
  src/routes.php
Labels: Reviewed

#252 S3 us34 admin add cat tissus
  config/config.php
  public/uploads/.gitignore
  src/Controller/AdminClothCategoryController.php
  src/Model/ClothCategoryManager.php
  src/View/Admin/ClothCategory/_form.html.twig
  src/View/Admin/ClothCategory/add.html.twig
  src/View/Admin/ClothCategory/index.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#250 S2 us10 view card
  public/assets/css/tips.css
  src/Controller/TipsController.php
  src/Model/TipsManager.php
  src/View/Tips/show.html.twig
  src/View/Tips/tips.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#255 S03 us27 admin tips index
  src/Controller/AdminTipController.php
  src/Model/AdminTipManager.php
  src/View/Admin/Tips/index.html.twig
  src/routes.php
Labels: Reviewed, Conflicts resolved

#263 manager fix
  src/Controller/AdminClothController.php
  src/Controller/ItemController.php
  src/Model/CategoryManager.php
  src/Model/ItemManager.php
Labels: Reviewed, Fix

#253 S02 us12 tutorials
  database.sql
  public/assets/css/tutorials.css
  src/Controller/TutorialController.php
  src/Model/TutorialManager.php
  src/View/Tutorials/index.html.twig
  src/View/Tutorials/show.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#261 S3 us36 admin edit cat tissus
  src/Controller/AdminClothCategoryController.php
  src/Model/ClothCategoryManager.php
  src/View/Admin/ClothCategory/edit.html.twig
  src/View/Admin/ClothCategory/index.html.twig
  src/routes.php
Labels: Reviewed, Conflicts resolved

#262 correction du message de validation plus style du bouton
  public/assets/css/contact.css
  src/Controller/ContactController.php
  src/View/Contact/contact.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#272 Megafix managers
  src/Controller/AdminClothController.php
  src/Controller/AdminLexiconController.php
  src/Controller/AdminMachineController.php
  src/Controller/AdminTipController.php
  src/Controller/HomeController.php
  src/Controller/TipController.php
  src/Model/AdminClothManager.php
  src/Model/AdminLexiconManager.php
  src/Model/AdminMachineManager.php
  src/Model/AdminTipManager.php
  src/Model/ClothManager.php
  src/Model/HomeClothManager.php
  src/Model/HomeMachineManager.php
  src/Model/LexiconManager.php
  src/Model/MachineManager.php
  src/Model/TipManager.php
  src/routes.php
Labels: Conflicts resolved

#271 S3US37-admin-delete-cat-tissus
  src/Controller/AdminClothCategoryController.php
  src/View/Admin/ClothCategory/index.html.twig
  src/routes.php
Labels: Reviewed, Conflicts resolved

#274 Tips fix
  src/View/Tips/tips.html.twig
  src/routes.php
Labels: Reviewed, Fix

#275 db.php.dist is back!
  config/db.php.dist
Labels: Reviewed, Fix

#260 S3 us31 lexicon show
  src/Controller/AdminLexiconController.php
  src/View/Admin/Lexicon/index.html.twig
  src/routes.php
Labels: Review needed, Conflicts resolved

#257 S3 us42 form
  src/Controller/AdminClothController.php
  src/Model/AdminClothManager.php
  src/View/Admin/Cloth/_form.html.twig
Labels: Reviewed, Conflicts resolved

#281 fixed navbar links
  src/View/Admin/Component/_navbar.html.twig
Labels: Reviewed, Fix

#280 S03US29 admin tips delete
  src/Controller/AdminTipController.php
  src/View/Admin/Tips/index.html.twig
  src/routes.php
Labels: Reviewed

#283 fix footer button top and facebook
  public/assets/css/footer.css
  src/View/Component/_footer.html.twig
Labels: Reviewed

#284 S03 us41 admin cloth image
  src/Controller/AdminClothController.php
  src/Model/AdminClothManager.php
  src/Model/ClothManager.php
  src/View/Admin/Cloth/_form.html.twig
Labels: Reviewed

#286 fix slogan
  public/assets/css/home.css
  public/assets/css/slogan.css
  public/assets/css/style.css
Labels: Reviewed

#245 finish view machineUser 1.0
  src/Controller/MachineController.php
  src/Model/MachineManager.php
  src/View/Products/Machines/index.html.twig
  src/View/Products/Machines/show.html.twig
  src/routes.php
Labels: Conflicts resolved

#276 S3-US32-AdminLexiconDelete
  src/Controller/AdminLexiconController.php
  src/View/Admin/Lexicon/index.html.twig
  src/routes.php
Labels: Conflicts resolved

#279 S03 us26 admin tips add
  database.sql
  public/assets/css/adminstyle.css
  src/Controller/AdminTipController.php
  src/Model/TipManager.php
  src/View/Admin/Tips/_form.html.twig
  src/View/Admin/Tips/add.html.twig
  src/View/Admin/Tips/index.html.twig
  src/routes.php
Labels: Review needed, Conflicts resolved

#282 S03 us39 admin tutorials index
  src/Controller/AdminTutorialController.php
  src/View/Admin/Tutorials/index.html.twig
  src/routes.php
Labels: Review needed, Conflicts resolved

#290 fix TipController dans routes
  src/routes.php
Labels: Reviewed, Fix

#292 S03 us28 admin tips edit
  src/Controller/AdminTipController.php
  src/Model/TipManager.php
  src/View/Admin/Tips/_form.html.twig
  src/View/Admin/Tips/edit.html.twig
  src/View/Admin/Tips/index.html.twig
  src/routes.php
Labels: Reviewed

#293 S03US45 admin tutorials delete
  src/Controller/AdminTutorialController.php
  src/routes.php
Labels: Reviewed

#289 Fix admin sv gediter
  src/View/Admin/Cloth/_form.html.twig
  src/View/Admin/Cloth/edit.html.twig
  src/View/Admin/ClothCategory/_form.html.twig
  src/View/Admin/ClothCategory/edit.html.twig
  src/View/Admin/Lexicon/_form.html.twig
  src/View/Admin/Lexicon/edit.html.twig
  src/View/Admin/Machine/_form.html.twig
  src/View/Admin/Machine/edit.html.twig
Labels: Conflicts resolved

#322 fix_controller_tip
  src/Controller/TipController.php
Labels: Reviewed

#323 Fix_style_tips
  public/assets/css/tips.css
  src/View/Tips/show.html.twig
  src/View/Tips/tips.html.twig
Labels: Reviewed

#341 fix_structuration_style_form
  src/View/Contact/contact.html.twig
Labels: Reviewed

#338 Fix barre de recherche tissus
  src/View/Products/Clothes/index.html.twig
  src/View/Products/Clothes/show.html.twig
Labels: Reviewed

#332 S3 us50 search
  public/assets/css/products.css
  src/Controller/ProductController.php
  src/Model/ClothManager.php
  src/Model/MachineManager.php
  src/View/Products/index.html.twig
  src/View/Products/search.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#344 fix - cards de la même taille dans view search
  public/assets/css/products.css
  src/View/Products/search.html.twig
Labels: Reviewed

#343 fix - barre de recherche dans la vue recherche
  src/View/Products/search.html.twig
Labels: Reviewed

#329 fix_header_form
  public/assets/css/contact.css
  public/assets/images/contact.jpg
  src/View/Contact/contact.html.twig
Labels: Conflicts resolved

#326 fix_zoom_button
  public/assets/css/home.css
  public/assets/css/products.css
  public/assets/css/tips.css
Labels: Conflicts resolved

#346 Fix responsive de home page
  public/assets/css/home.css
  src/View/Home/index.html.twig
Labels: Reviewed, Corrections done

#325 fix_sewing_button
  public/assets/css/contact.css
  public/assets/css/footer.css
  public/assets/css/tips.css
  src/View/Contact/contact.html.twig
  src/View/Tips/tips.html.twig
Labels: Conflicts resolved, wtf 🤷‍♂️

#350 Fix admin confirmation message
  src/View/Admin/Cloth/show.html.twig
  src/View/Admin/ClothCategory/index.html.twig
  src/View/Admin/Lexicon/index.html.twig
  src/View/Admin/Machine/show.html.twig
  src/View/Admin/Tips/index.html.twig
  src/View/Admin/Tutorials/index.html.twig
Labels: Reviewed

#349 fix - bouton catégorie qui se distingue
  public/assets/css/products.css
  src/View/Products/Clothes/index.html.twig
  src/View/Products/Clothes/show.html.twig
  src/View/Products/Machines/index.html.twig
  src/View/Products/Machines/show.html.twig
Labels: Reviewed, Corrections done

#354 Fix - image boutique
  public/assets/css/home.css
  public/assets/images/shop.jpeg
  src/View/Home/index.html.twig
Labels: Reviewed

#355 fix checked on admin cloth
  src/View/Admin/Cloth/_form.html.twig
Labels: Reviewed

#356 Fix admin edit machine checkbox
  src/View/Admin/Machine/_form.html.twig
Labels: Reviewed

#357 Admin fix machine description textarea
  src/View/Admin/Machine/_form.html.twig
Labels: Reviewed

#348 S3 us17 login
  database.sql
  phpmd.xml
  public/assets/css/login.css
  public/assets/css/navbarStyle.css
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/AdminClothCategoryController.php
  src/Controller/AdminClothController.php
  src/Controller/AdminController.php
  src/Controller/AdminLexiconController.php
  src/Controller/AdminMachineController.php
  src/Controller/AdminTipController.php
  src/Controller/LoginController.php
  src/Model/UserManager.php
  src/View/Admin/Cloth/show.html.twig
  src/View/Admin/ClothCategory/index.html.twig
  src/View/Admin/Component/_navbar.html.twig
  src/View/Admin/Home/index.html.twig
  src/View/Admin/Lexicon/index.html.twig
  src/View/Admin/Machine/show.html.twig
  src/View/Admin/Tips/index.html.twig
  src/View/Component/_footer.html.twig
  src/View/Login/login.html.twig
  src/routes.php
Labels: Corrections done, Conflicts resolved

#353 Admin fix description
  src/Model/ClothManager.php
  src/View/Admin/Cloth/_form.html.twig
Labels: Reviewed, Corrections done, Fix

#365 fix twig render lexicon admin
  src/Controller/AdminLexiconController.php
Labels: Reviewed, Fix

#366 Fix - image récupérées dans fetch pour search
  src/Model/ClothManager.php
  src/Model/MachineManager.php
  src/View/Products/search.html.twig
Labels: Reviewed, Fix

#368 login_route_fix
  src/Controller/LoginController.php
  src/View/Admin/Component/_navbar.html.twig
  src/routes.php
Labels: Reviewed, Fix

#371 fix du style admin sur catégories, tissus et lexique
  public/assets/css/adminstyle.css
  src/View/Admin/Cloth/_form.html.twig
  src/View/Admin/Cloth/show.html.twig
  src/View/Admin/ClothCategory/_form.html.twig
  src/View/Admin/ClothCategory/index.html.twig
  src/View/Admin/Lexicon/_form.html.twig
  src/View/Admin/Lexicon/index.html.twig
Labels: Reviewed

#369 S4 us49 home page admin
  public/assets/css/adminstyle.css
  src/View/Admin/Home/index.html.twig
  src/View/Login/login.html.twig
Labels: Reviewed

#373 Fix responsive catégories + zoom
  public/assets/css/lexicon.css
  public/assets/css/tips.css
  public/assets/css/tutorials.css
  src/View/Lexicon/index.html.twig
  src/View/Tips/show.html.twig
  src/View/Tips/tips.html.twig
  src/View/Tutorials/index.html.twig
  src/View/Tutorials/show.html.twig
Labels: Reviewed

#420 fix config dist mailer dsn
  config/db.php.dist
Labels: Reviewed, Fix

#428 Fix - query string recherche produit vide par défaut
  src/Controller/ProductController.php
Labels: Reviewed

#375 fix_monthlyTips
  public/assets/css/tips.css
  src/View/Tips/tips.html.twig
Labels: Conflicts resolved

#433 fix orthographe
  database.sql
  src/View/Component/_footer.html.twig
Labels: Reviewed, Fix

#434 fix_scroll_tips
  src/View/Lexicon/index.html.twig
  src/View/Tips/tips.html.twig
  src/View/Tutorials/index.html.twig
Labels: Reviewed, Fix

#439 Fix - images sur page d'accueil en bdd
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#438 Admin fix tutorials tips machines style
  src/View/Admin/Lexicon/_form.html.twig
  src/View/Admin/Lexicon/index.html.twig
  src/View/Admin/Machine/_form.html.twig
  src/View/Admin/Machine/show.html.twig
  src/View/Admin/Tips/_form.html.twig
  src/View/Admin/Tips/index.html.twig
  src/View/Admin/Tutorials/_form.html.twig
  src/View/Admin/Tutorials/index.html.twig
Labels: Reviewed, Fix

#432 Fix admin cloth form
  src/Controller/AdminClothController.php
  src/Model/ClothManager.php
  src/View/Admin/Cloth/_form.html.twig
Labels: Reviewed, Corrections done, Fix

#443 Fix footer tel
  src/View/Component/_footer.html.twig
Labels: Reviewed

#447 fix - images catégories
  database.sql
  public/assets/images/creative.jpeg
  public/assets/images/decoration.jpeg
  public/assets/images/furniturefabric.jpeg
  public/assets/images/machinecat.jpeg
  public/assets/images/mercerie.jpeg
  public/assets/images/sewingfabric.jpeg
  public/assets/images/voilage.jpeg
  src/View/Products/index.html.twig
Labels: Reviewed, Fix

#446 fix admin machines images
  src/Controller/AdminMachineController.php
  src/Model/MachineManager.php
Labels: Reviewed, Fix

#448 fixed on cascade in db
  database.sql
Labels: Reviewed, Fix

#450 Fix -cards home
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#452 fix - responsive sur toutes les pages produits
  public/assets/css/products.css
  src/View/Products/Clothes/index.html.twig
  src/View/Products/Clothes/show.html.twig
  src/View/Products/Machines/index.html.twig
  src/View/Products/Machines/show.html.twig
  src/View/Products/index.html.twig
  src/View/Products/search.html.twig
Labels: Fix, Conflicts resolved

#444 Megafix images admin
  src/Model/ClothCategoryManager.php
  src/Model/ClothManager.php
  src/Model/MachineManager.php
  src/Model/TipManager.php
  src/Model/TutorialManager.php
  src/View/Admin/Cloth/_form.html.twig
  src/View/Admin/ClothCategory/_form.html.twig
  src/View/Admin/Lexicon/_form.html.twig
  src/View/Admin/Machine/_form.html.twig
  src/View/Admin/Tips/_form.html.twig
  src/View/Admin/Tutorials/_form.html.twig
Labels: Reviewed, Fix, Conflicts resolved

#456 fix responsive home
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#457 fixfaviconadmin
  src/View/layout.html.twig
Labels: Reviewed, Fix, wtf 🤷‍♂️

#458 Fix - catégories trucs et astuces mises en valeur
  src/View/Lexicon/index.html.twig
  src/View/Tips/show.html.twig
  src/View/Tips/tips.html.twig
  src/View/Tutorials/index.html.twig
  src/View/Tutorials/show.html.twig
Labels: Reviewed, Fix

#461 fixtelfooter
  src/View/Component/_footer.html.twig
Labels: Reviewed

#464 fix admin remove green alert
  src/View/Admin/Cloth/show.html.twig
  src/View/Admin/ClothCategory/index.html.twig
  src/View/Admin/Lexicon/index.html.twig
  src/View/Admin/Machine/show.html.twig
  src/View/Admin/Tips/index.html.twig
  src/View/Admin/Tutorials/index.html.twig
Labels: Reviewed, Fix

#468 fixboutoncontact
  src/View/Contact/contact.html.twig
Labels: Reviewed, Fix

#467 fixed lexicon admin
  src/Controller/AdminLexiconController.php
  src/Model/LexiconManager.php
  src/View/Admin/Lexicon/_form.html.twig
Labels: Reviewed, Corrections done, Fix

#471 Fix - header contact
  public/assets/css/contact.css
  public/assets/images/headercontact.jpeg
Labels: Reviewed, Fix

#459 fix_responsive_Tips
  public/assets/css/lexicon.css
  public/assets/css/tips.css
  public/assets/css/tutorials.css
  src/View/Lexicon/index.html.twig
  src/View/Tips/show.html.twig
  src/View/Tips/tips.html.twig
  src/View/Tutorials/show.html.twig
Labels: Conflicts resolved

#474 Fix deconnexion
  public/assets/css/adminstyle.css
  src/View/Admin/Component/_navbar.html.twig
Labels: Reviewed

#469 fix admin cloth caps
  src/View/Admin/Cloth/add.html.twig
  src/View/Admin/Cloth/edit.html.twig
Labels: Reviewed, Fix

#462 Fix lexicon style
  public/assets/css/lexicon.css
  src/View/Lexicon/index.html.twig
Labels: Reviewed, Corrections done

#466 Fix - style admin
  public/assets/css/adminstyle.css
  src/View/Admin/Component/_navbar.html.twig
  src/View/Admin/Home/index.html.twig
Labels: Reviewed, Corrections done, Fix

#476 fix admin tips redirect
  src/View/Admin/Tips/index.html.twig
Labels: Reviewed, Fix

#477 Fix - catégories tutoriels show
  src/View/Tutorials/show.html.twig
Labels: Reviewed

#478 Fix admin lexicon add
  src/Controller/AdminLexiconController.php
  src/Model/LexiconManager.php
Labels: Reviewed, Fix

#479 fix_footer_icon_title
  public/assets/css/footer.css
  src/View/Component/_footer.html.twig
Labels: Reviewed

#475 fix admin image categories
  src/Controller/AdminClothCategoryController.php
  src/View/Admin/ClothCategory/_form.html.twig
Labels: Reviewed, Fix

#480 Fix affichage des nouveaux produits
  public/assets/css/products.css
  src/View/Products/Clothes/index.html.twig
  src/View/Products/Clothes/show.html.twig
  src/View/Products/Machines/index.html.twig
Labels: Reviewed
