Repository WildCodeSchool/2022-03-php-orleans-project-tissusjaures, pull requests merged in 2022-04, with the labels that each got.

#1 Initialisation
  .DS_Store
  composer.lock
  public/.DS_Store
  public/assets/css/style.css
  src/.DS_Store
  src/View/layout.html.twig
Labels: Review needed, Reviewed, Corrections done

#61 S1 us1 navbar
  public/assets/css/navbarStyle.css
  public/assets/css/style.css
  src/View/Component/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Corrections done

#64 S01 us18 cloth admin
  .gitignore
  composer.lock
  config/db.php.dist
  database.sql
  public/assets/css/adminstyle.css
  public/assets/images/mchn1.jpg
  public/assets/images/tss1.jpg
  src/Controller/AdminClothController.php
  src/Model/AdminClothManager.php
  src/Model/CategoryManager.php
  src/View/Admin/Cloth/_form.html.twig
  src/View/Admin/Cloth/add.html.twig
  src/View/adminLayout.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#68 removed useless title
  src/View/Home/index.html.twig
  src/View/adminLayout.html.twig
Labels: Reviewed

#66 S1 us2 footer
  public/assets/css/footer.css
  public/assets/css/style.css
  src/View/Component/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Corrections done

#69 Dev to main
  .DS_Store
  .gitignore
  composer.lock
  config/db.php.dist
  database.sql
  public/.DS_Store
  public/assets/css/adminstyle.css
  public/assets/css/footer.css
  public/assets/css/navbarStyle.css
  public/assets/css/style.css
  public/assets/images/mchn1.jpg
  public/assets/images/tss1.jpg
  src/.DS_Store
  src/Controller/AdminClothController.php
  src/Model/AdminClothManager.php
  src/Model/CategoryManager.php
  src/View/Admin/Cloth/_form.html.twig
  src/View/Admin/Cloth/add.html.twig
  src/View/Component/_footer.html.twig
  src/View/Component/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/adminLayout.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed

#110 change font size link
  public/assets/css/navbarStyle.css
  public/assets/css/style.css
Labels: Reviewed

#62 16 home
  .DS_Store
  .gitignore
  database.sql
  public/.DS_Store
  public/assets/css/home.css
  public/assets/css/style.css
  public/assets/images/header.jpeg
  src/.DS_Store
  src/Controller/HomeController.php
  src/Model/HomeClothManager.php
  src/Model/HomeMachineManager.php
  src/View/Component/_slogan.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Corrections done

#112 Fix_admincloth
  public/assets/css/adminstyle.css
  src/Controller/AdminClothController.php
  src/View/Admin/Cloth/_form.html.twig
  src/View/adminLayout.html.twig
Labels: Reviewed, Corrections done

#118 S02 s20 admin cloth edit
  src/Controller/AdminClothController.php
  src/Model/AdminClothManager.php
  src/View/Admin/Cloth/_form.html.twig
  src/View/Admin/Cloth/show.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#122 hello darkness my old friend
  database.sql
Labels: Reviewed

#128 Fix home
  public/assets/css/home.css
  public/assets/images/header.jpeg
  public/assets/images/headermain.jpeg
  src/View/Home/index.html.twig
Labels: Reviewed, Corrections done

#124 S2 us 22 catégories machines
  src/Controller/AdminMachineController.php
  src/Model/AdminMachineManager.php
  src/View/Admin/Machine/_form.html.twig
  src/View/Admin/Machine/add.html.twig
Labels: Reviewed, Corrections done

#129 fix home 2
  src/View/Home/index.html.twig
Labels: Reviewed

#130 S2 us 23 la machine
  src/Controller/AdminMachineController.php
  src/Model/AdminMachineManager.php
  src/View/Admin/Machine/show.html.twig
  src/routes.php
Labels: Reviewed

#134 Fix dev again
  public/assets/css/footer.css
  public/assets/css/style.css
  src/View/Component/_footer.html.twig
  src/View/Component/_slogan.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Fix

#132 fixed routes and links
  src/Controller/AdminClothController.php
  src/Controller/AdminMachineController.php
  src/View/Admin/Cloth/show.html.twig
  src/View/Admin/Machine/show.html.twig
  src/routes.php
Labels: Reviewed, Fix

#133 S2 us24 delete machine
  src/Controller/AdminMachineController.php
  src/View/Admin/Machine/show.html.twig
  src/routes.php
Labels: Reviewed, Corrections done, Fix

#131 S2 us13 monthly tips
  database.sql
  public/assets/css/tips.css
  public/assets/images/imgtip.jpg
  public/assets/images/tipheader.jpg
  src/Controller/TipsController.php
  src/Model/TipsManager.php
  src/View/Tips/tips.html.twig
  src/routes.php
Labels: Conflicts resolved

#138 Fix liensnavbar
  src/View/Component/_navbar.html.twig
Labels: Reviewed, Fix

#119 S1 us11 form
  public/assets/css/contact.css
  public/assets/css/style.css
  src/Controller/ContactController.php
  src/View/Item/_form.html.twig
  src/View/contact.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#144 fixed broken link
  src/View/Admin/Cloth/show.html.twig
Labels: Reviewed, Fix

#120 Us15 tissus
  public/assets/css/products.css
  src/Controller/ClothController.php
  src/Model/ClothManager.php
  src/View/Products/index.html.twig
  src/View/Products/tissus.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed, Conflicts resolved

#140 S2 us25 machine edit
  src/Controller/AdminMachineController.php
  src/Model/AdminMachineManager.php
  src/View/Admin/Machine/edit.html.twig
  src/View/Admin/Machine/show.html.twig
  src/routes.php
Labels: Reviewed
